# Generated by Django 4.2.1 on 2023-05-30 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='appointment date')),
                ('time', models.DateTimeField(verbose_name='appointment time')),
                ('status', models.CharField(choices=[('SC', 'Scheduled'), ('CA', 'Cancelled'), ('CO', 'Completed')], default='SC', max_length=2)),
            ],
        ),
    ]
