# Generated by Django 4.2.1 on 2023-07-03 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_location_alter_appointment_date_appointment_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appointments.location'),
        ),
    ]
