# Generated by Django 4.2.1 on 2023-07-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointment_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='phone_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(verbose_name='Appointment Date'),
        ),
    ]
